name: Build and Deploy Jupyter Book

on:
  push:
    branches:
      - main  # Vervang 'main' door de naam van je hoofdbranch indien nodig

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Kies de juiste Python-versie

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter-book
        pip install -r requirements.txt

    - name: Build Jupyter Book
      run: jupyter-book build .

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.J8 }}
        publish_dir: ./_build/html  # Pad naar de HTML-build van je Jupyter Book
